#ifndef _OLED_CONFIG_H
#define _OLED_CONFIG_H

#define OLED_HEIGHT     32
#define OLED_WIDTH      128
#define OLED_ADDR	0x78

#define OLED_FLIP_VERTICALLY	1
#define OLED_FLIP_HORIZONTALLY	1


#define OLED_FONT_USE_DEFAULT_5X7 1
#define OLED_FONT_USE_DEFAULT_6X7 1
#define OLED_FONT_USE_ARIAL_14	1

#endif
