#ifndef _OLED_CONFIG_H
#define _OLED_CONFIG_H

#define OLED_HEIGHT     32
#define OLED_WIDTH      128
#define OLED_ADDR	0x78

#define OLED_FLIP_VERTICALLY	1
#define OLED_FLIP_HORIZONTALLY	1


#define OLED_FONT_USE_DEFAULT_5X7	1
#define OLED_FONT_USE_DEFAULT_6X7	1
#define OLED_FONT_USE_ARIAL_14		1
#define OLED_FONT_USE_IAIN_5X7		1
#define OLED_FONT_USE_SYSTEM_5X7	1
#define OLED_FONT_USE_STANG_5X7 	1
#define OLED_FONT_USE_WENDY_3X5 	1
#define OLED_FONT_USE_CP437_8X8		1
#define OLED_FONT_USE_FONT_8X8		1

#endif
