#ifndef _GFX_CONFIG_H
#define _GFX_CONFIG_H

#define GFX_FONT_USE_DEFAULT_5X7	0
#define GFX_FONT_USE_DEFAULT_6X7	0
#define GFX_FONT_USE_ARIAL_14		0
#define GFX_FONT_USE_IAIN_5X7		0
#define GFX_FONT_USE_SYSTEM_5X7	0
#define GFX_FONT_USE_STANG_5X7 	0
#define GFX_FONT_USE_WENDY_3X5 	0
#define GFX_FONT_USE_CP437_8X8		1
#define GFX_FONT_USE_FONT_8X8		0
#define GFX_FONT_USE_FIXED_BOLD	0
#define GFX_FONT_USE_COOPER_21		0
#define GFX_FONT_USE_TIMES_NEW_ROMAN_ITALIC 0

#endif
